### PR TITLE
Tracer implements Closeable

### PR DESCRIPTION
**Pull request by pavolloffay**

### CODE REVIEW

**Comment by jpkrohling** [comment]
Shouldn't be hard to write a test for this :) Other than that, LGTM

**Comment by jpkrohling** [comment]
I would expect the test to be like the `testClose`, but with a `try-with-resources` approach. But ensuring it implements the proper interface + keeping the `testClose` would be enough.

**Comment by pavolloffay** [comment]
Can somebody merge? (I don't have write access)

**Comment by jpkrohling** [comment]
Looks like I can't:

image

**Comment by yurishkuro** [comment]
any idea what's up with coverage? why does it show a drop in a file that should not be affected?

**Pull request merged**
