### PR TITLE
Senders fix, do not use static thrift factory

### PR DESCRIPTION
**Pull request by pavolloffay**
When I was using multiple tracers in one process `HttpSender` was sending corrupted data.

### CODE REVIEW

**Comment by pavolloffay** [comment]
We would have to emulate deserialization on the server size. 

Could we get it in and if necessary write test in separate PR? It's blocking my work `spark-depenencies` PR https://github.com/pavolloffay/spark-dependencies/pull/1.

**Comment by pavolloffay** [comment]
Once this is merged. Could you please do micro release? (I don't have rights and @jpkrohling  will be here on Wednesday)

**Comment by vprithvi** [comment]
Yeah, we can write a test as a separate PR. I'll merge and release

**Comment by yurishkuro** [comment]
@pavolloffay are you saying the factory is not thread safe?

**Comment by pavolloffay** [comment]
I haven't digged very deep. I will write a test later and look more closely.

**Comment by vprithvi** [comment]
The serializer isn't threadsafe, but looking at https://github.com/apache/thrift/blob/master/lib/java/src/org/apache/thrift/protocol/TBinaryProtocol.java#L85 it seems that we should be able to continue having the factory as static.

**Pull request merged**
